language: python
python:
  - 3.6
  - 3.7
  - 3.8
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"
    - "$HOME/.cache/pypoetry"
    - "$HOME/google-cloud-sdk/"

env:
  global:
    - secure: "psR/z9CYiKlNb5nkb+wAFu8MHezoxoPJBd2A8oOX8Heb6mzIfIrz0PJyNmTgipT3REYNeSES59a6iiugGr4ApD/FXaYSFa26Xpot4ghdlEf4nqLefB78zgvp+xtRvP1zvACLunEUKECA6N14iYrHNaq7RVf2EkvOMY3iLyWM1PgNWdZ+QvwoxBDAMzqjZHbrnfzFnSzpDLxGMyELzL/PFamtTHL6Byripr83XsDtbJER2W1pCqp09mR8KqRfeJCdMHlCC8osqGHRdNgT4iht6UbiJcL7NxqkqcrW2lAaueMXDoZyvYDOajyHdeS3F+tQzHW9FV9zDrt3W4EOfKfs+I6KDzJbMRyA/udAYq+Hw6ke6Ckj03Q/4wVEvm4GXZSlc1iR81UTNzM83AkeLvpiGZYHpTPfC73+tuqOZ20KRzeJnZXsIcn99RDwexT8+FKI15Tg2WBtxxEz1y6jyN1fn5B7E++b5LEW3ajkAKxRx93EGvsk/mzf0wOIYO7E/l0LqzKo7YDoUmtTDUYAJ6SyIccrAUSHaSWrPtOMUf7UHZGEj9fz36mlCQVQL4Abm+WUEZCR6P8JkYUpEZsTzSOTChe3UY13FcKnfO0yWHRY4tQngDxgSNAQ5JSarzqcVnmfOuosV0U4Ss8OFwyyC9VCBOdkwULvTyjoADaTMFbUiS4="

before_install:
  - nvm install
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf
    $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl
    https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - gcloud components install beta cloud-firestore-emulator --quiet
  - pip install poetry pre-commit

install:
  - poetry install

script:
  # Start the firestore emulator to be able to run the tests.
  - gcloud beta emulators firestore start --host-port=127.0.0.1:8686 > /dev/null 2>&1 &
  - poetry run invoke test

before_deploy:
  - poetry config pypi-token.pypi $PYPI_PASSWORD

deploy:
  - provider: script
    skip_existing: true
    script: poetry publish --build
    on:
      branch: master
      tags: true
      condition: "$TRAVIS_PYTHON_VERSION == 3.6"
