
[tool.poetry]
name = "firedantic"
version = "0.1.4"
description = "Pydantic base model for Firestore"
authors = ["Digital Living International Ltd"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/digitalliving/firedantic"
packages = [
    {include="firedantic", from="."}
]

[tool.poetry.dependencies]
python = ">=3.6.1,<4.0"
pydantic = "^1.8.1"
google-cloud-firestore = {git = "https://github.com/googleapis/python-firestore", rev = "e57258c51e4b4aa664cc927454056412756fc7ac"}
grpcio = "^1.36.1"

[tool.poetry.dev-dependencies]
isort = "^5.5.2"
invoke = "^1.4.1"
mypy = "^0.782"
flake8 = "^3.8.3"
pytest = "^6.0.2"
pydevd_pycharm = "^202.7319.37"
pytest-asyncio = "^0.14.0"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
